# https://probot.github.io/apps/settings/

repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: Member-Sumbissions

  # A short description of the repository that will show up on GitHub
  description: The first official batch of GVP-Ai-Club Student Chapter :computer:

  # A URL with more information about the repository
  homepage: #

  # Either `true` to make the repository private, or `false` to make it public.
  private: public

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: true

  # Updates the default branch for this repository.
  default_branch: master

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

# Labels: define labels for Issues and Pull Requests
labels:
  - name: help
    color: fbca04
  - name: week-1
    color: D71E3C
  - name: week-2
    color: D71E3C
  - name: bug
    color: 0000CC
  - name: feature-request
    color: 00CC00
  - name: discussion
    color: CC00CC
  - name: submission
    color: 00CCCC
  - name: announcement
    color: fbca04
  - name: subscribe-to-me
    color: fbca04
  - name: question
    color: fbca04
  - name: exempt
    color: fbca04
  - name: rude
    color: fbca04
